# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"Q\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x17\n\x0fhashed_password\x18\x04 \x01(\t\"A\n\x0cRegisterUser\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"1\n\x05Token\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t\"\x1d\n\tTokenData\x12\x10\n\x08username\x18\x01 \x01(\t\"-\n\nUserUpdate\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"N\n\x0cRefreshToken\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\r\n\x05token\x18\x03 \x01(\t\x12\x12\n\nexpires_at\x18\x04 \x01(\t\",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"P\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t\x12\x15\n\rrefresh_token\x18\x03 \x01(\t\"!\n\x10RefreshTokenData\x12\r\n\x05\x65mail\x18\x01 \x01(\t\";\n\x07UserAll\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=20
  _globals['_USER']._serialized_end=101
  _globals['_REGISTERUSER']._serialized_start=103
  _globals['_REGISTERUSER']._serialized_end=168
  _globals['_TOKEN']._serialized_start=170
  _globals['_TOKEN']._serialized_end=219
  _globals['_TOKENDATA']._serialized_start=221
  _globals['_TOKENDATA']._serialized_end=250
  _globals['_USERUPDATE']._serialized_start=252
  _globals['_USERUPDATE']._serialized_end=297
  _globals['_REFRESHTOKEN']._serialized_start=299
  _globals['_REFRESHTOKEN']._serialized_end=377
  _globals['_REFRESHTOKENREQUEST']._serialized_start=379
  _globals['_REFRESHTOKENREQUEST']._serialized_end=423
  _globals['_LOGINRESPONSE']._serialized_start=425
  _globals['_LOGINRESPONSE']._serialized_end=505
  _globals['_REFRESHTOKENDATA']._serialized_start=507
  _globals['_REFRESHTOKENDATA']._serialized_end=540
  _globals['_USERALL']._serialized_start=542
  _globals['_USERALL']._serialized_end=601
# @@protoc_insertion_point(module_scope)
