# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"S\n\tInventory\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x14\n\x0cstatus_stock\x18\x04 \x01(\t\"M\n\x0fInventoryCreate\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x14\n\x0cstatus_stock\x18\x03 \x01(\t\"9\n\x0fInventoryUpdate\x12\x10\n\x08quantity\x18\x01 \x01(\x05\x12\x14\n\x0cstock_status\x18\x02 \x01(\t\"[\n\x11InventoryResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x14\n\x0cstatus_stock\x18\x04 \x01(\t\"\x92\x02\n\x12InventoryOperation\x12\x39\n\x0eoperation_type\x18\x01 \x01(\x0e\x32!.inventory.InventoryOperationType\x12)\n\tinventory\x18\x02 \x01(\x0b\x32\x14.inventory.InventoryH\x00\x12\x36\n\x10inventory_create\x18\x03 \x01(\x0b\x32\x1a.inventory.InventoryCreateH\x00\x12\x36\n\x10inventory_update\x18\x04 \x01(\x0b\x32\x1a.inventory.InventoryUpdateH\x00\x12\x14\n\nproduct_id\x18\x05 \x01(\x05H\x00\x42\x10\n\x0einventory_data*E\n\x16InventoryOperationType\x12\n\n\x06\x43REATE\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x12\x07\n\x03GET\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVENTORYOPERATIONTYPE']._serialized_start=623
  _globals['_INVENTORYOPERATIONTYPE']._serialized_end=692
  _globals['_INVENTORY']._serialized_start=30
  _globals['_INVENTORY']._serialized_end=113
  _globals['_INVENTORYCREATE']._serialized_start=115
  _globals['_INVENTORYCREATE']._serialized_end=192
  _globals['_INVENTORYUPDATE']._serialized_start=194
  _globals['_INVENTORYUPDATE']._serialized_end=251
  _globals['_INVENTORYRESPONSE']._serialized_start=253
  _globals['_INVENTORYRESPONSE']._serialized_end=344
  _globals['_INVENTORYOPERATION']._serialized_start=347
  _globals['_INVENTORYOPERATION']._serialized_end=621
# @@protoc_insertion_point(module_scope)
