# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\"\xc7\x01\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\x12\x14\n\x0cproduct_name\x18\x04 \x01(\t\x12\x10\n\x08quantity\x18\x05 \x01(\x05\x12\x18\n\x10shipping_address\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x12\n\ncreated_at\x18\x08 \x01(\t\x12\x12\n\nupdated_at\x18\t \x01(\t\x12\x13\n\x0btotal_price\x18\n \x01(\x02\"Z\n\x0cOrderMessage\x12\x1c\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0c.MessageType\x12\x1a\n\norder_data\x18\x02 \x01(\x0b\x32\x06.Order\x12\x10\n\x08order_id\x18\x03 \x01(\x05*R\n\x0bMessageType\x12\x10\n\x0c\x43REATE_ORDER\x10\x00\x12\x10\n\x0cUPDATE_ORDER\x10\x01\x12\x10\n\x0c\x44\x45LETE_ORDER\x10\x02\x12\r\n\tGET_ORDER\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPE']._serialized_start=309
  _globals['_MESSAGETYPE']._serialized_end=391
  _globals['_ORDER']._serialized_start=16
  _globals['_ORDER']._serialized_end=215
  _globals['_ORDERMESSAGE']._serialized_start=217
  _globals['_ORDERMESSAGE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
