# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\"F\n\x0bOrderUpdate\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x14\n\x0corder_status\x18\x03 \x01(\t\"!\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"|\n\x13NotificationMessage\x12\x31\n\x0corder_update\x18\x01 \x01(\x0b\x32\x19.notification.OrderUpdateH\x00\x12\"\n\x04user\x18\x02 \x01(\x0b\x32\x12.notification.UserH\x00\x42\x0e\n\x0cmessage_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERUPDATE']._serialized_start=36
  _globals['_ORDERUPDATE']._serialized_end=106
  _globals['_USER']._serialized_start=108
  _globals['_USER']._serialized_end=141
  _globals['_NOTIFICATIONMESSAGE']._serialized_start=143
  _globals['_NOTIFICATIONMESSAGE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
